services:
  nginx:
    image: nginx:alpine
    ports:
      - "11434:11434"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    ports:
      - "80:80"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"
    restart: unless-stopped

# Commands to get certificates:
# sudo docker compose run --rm certbot certonly --webroot -w /var/www/certbot -d ollama.wg.dphx.eu
