services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik/config:/etc/traefik/config
      - ./data/traefik/certificates:/etc/traefik/certificates
      - ./data/traefik/acme:/etc/traefik/acme